# Generated by Django 5.0.6 on 2024-06-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=255)),
                ('is_self', models.BooleanField()),
                ('message_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['chat_id', 'timestamp'], name='api_message_chat_id_25a4f5_idx')],
            },
        ),
    ]
